from __future__ import annotations

from dash import Input, Output, State


def register_strategy_callbacks(app, *, run_backtest_func, update_tab_func) -> None:
    @app.callback(
        Output("backtest-store", "data"),
        [
            Input("run-btn", "n_clicks"),
            Input("auto-run", "value"),
            Input("hide-strategy-presets", "value"),
            Input("ticker-dropdown", "value"),
            Input("start-date", "value"),
            Input("end-date", "value"),
            Input("discount-slider", "value"),
            Input("cooldown-bars", "value"),
            Input("bad-holding", "value"),
            Input("crash-overlay-switch", "value"),
            Input("crash-overlay-preset", "value"),
            Input("warehouse-dropdown", "value"),
            Input("majority-floor", "value"),
            Input("majority-ema-span", "value"),
            Input("majority-delta-cap", "value"),
            Input("majority-min-cooldown", "value"),
            Input("majority-min-trade-dw", "value"),
            Input("prop-floor", "value"),
            Input("prop-ema-span", "value"),
            Input("prop-delta-cap", "value"),
            Input("prop-min-cooldown", "value"),
            Input("prop-min-trade-dw", "value"),
        ],
        State("backtest-store", "data"),
    )
    def _run_backtest_callback(
        n_clicks,
        auto_run,
        hidden_strategy_presets,
        ticker,
        start_date,
        end_date,
        discount,
        cooldown,
        bad_holding,
        crash_overlay_on,
        crash_overlay_preset,
        warehouse_file,
        maj_floor,
        maj_ema,
        maj_delta,
        maj_cooldown,
        maj_dw,
        prop_floor,
        prop_ema,
        prop_delta,
        prop_cooldown,
        prop_dw,
        stored_data,
    ):
        return run_backtest_func(
            n_clicks,
            auto_run,
            hidden_strategy_presets,
            ticker,
            start_date,
            end_date,
            discount,
            cooldown,
            bad_holding,
            crash_overlay_on,
            crash_overlay_preset,
            warehouse_file,
            maj_floor,
            maj_ema,
            maj_delta,
            maj_cooldown,
            maj_dw,
            prop_floor,
            prop_ema,
            prop_delta,
            prop_cooldown,
            prop_dw,
            stored_data,
        )

    @app.callback(
        Output("tab-content", "children"),
        Input("backtest-store", "data"),
        Input("main-tabs", "value"),
        Input("theme-store", "data"),
        Input("smart-leverage-switch", "value"),
        Input("hide-strategy-presets", "value"),
        Input("ticker-dropdown", "value"),
    )
    def _update_tab_callback(data, tab, theme, smart_leverage_on, hidden_strategy_presets, ticker_for_daily):
        return update_tab_func(data, tab, theme, smart_leverage_on, hidden_strategy_presets, ticker_for_daily)
